
---
include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
  - board: nice_nano_v2
    shield: corne_dongle pro_micro_i2c
  - board: nice_nano_v2
    shield: settings_reset