
---
include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
  - board: nice_nano_v2
    shield: corne_dongle nice_oled
  - board: nice_nano_v2
    shield: settings_reset